### ISSUE TITLE
nb2to3

### ISSUE THREAD

**Issue by choldgraf** [profjsb/python-bootcamp#5]
Just a quick thing I think the conversion script misses. I was getting an error when Python tried to annotate a plot. Here's the line in question:

`ax.text(3, 2, str("unicode: Institut f\374r Festk\366rperphysik", "latin-1"), fontsize=18)`

I was getting the following error:

`TypeError: decoding str is not supported`

I found [this stackoverflow post](http://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal), and tried putting a `b` in front of the string. That solved the problem.

`ax.text(3, 2, str(b"unicode: Institut f\374r Festk\366rperphysik", "latin-1"), fontsize=18)`

So perhaps this is something that the conversion tool could look for as well? Any time someone invokes `str(` followed by a string that doesn't begin with `b` followed by any extra arguments, it appends the `b` in there?

**Comment by marwahaha** [comment]
@takluyver

**Comment by takluyver** [comment]
The conversion tool is just running the `2to3` fixers on each code cell, it doesn't actually analyse the code itself. If you want to write your own fixers, I think that's possible (look at python-modernize for an example of defining extra fixers), but I'd guess things like this are rare enough that it's easier to fix them by hand.

**Comment by choldgraf** [comment]
Fair enough - just wanted to bring this to attention just in case...I'll close the issue
